"""add id Paymentrequests

Revision ID: 2fac093ada16
Revises: 8eadf2bf679a
Create Date: 2024-03-28 01:37:01.908671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fac093ada16'
down_revision: Union[str, None] = '8eadf2bf679a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_requests', sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_requests', 'id')
    # ### end Alembic commands ###
