"""changes

Revision ID: 412fe5257fac
Revises: bed334079be0
Create Date: 2024-03-30 15:54:02.104787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '412fe5257fac'
down_revision: Union[str, None] = 'bed334079be0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_requests', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'payment_requests', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payment_requests', type_='foreignkey')
    op.drop_column('payment_requests', 'user_id')
    # ### end Alembic commands ###
