"""payments model edit

Revision ID: 752d4ebb92fa
Revises: 9668391beeb4
Create Date: 2024-02-29 23:51:33.532765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '752d4ebb92fa'
down_revision: Union[str, None] = '9668391beeb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('operation_id', sa.String(), nullable=False))
    op.add_column('payments', sa.Column('operation_label', sa.String(), nullable=False))
    op.drop_column('payments', 'wallet_operation_id')
    op.drop_column('payments', 'codepro')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('codepro', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('payments', sa.Column('wallet_operation_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('payments', 'operation_label')
    op.drop_column('payments', 'operation_id')
    # ### end Alembic commands ###
