"""init

Revision ID: 9668391beeb4
Revises: 
Create Date: 2024-02-28 00:18:05.319676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9668391beeb4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_types',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('telegram_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('xray_uuid', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('start', sa.Date(), nullable=False),
    sa.Column('stop', sa.Date(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subscription_type', sa.String(), nullable=False),
    sa.Column('payment_label', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['subscription_type'], ['subscription_types.name'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('notification_type', sa.String(), nullable=False),
    sa.Column('wallet_operation_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('withdraw_amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.Integer(), nullable=False),
    sa.Column('api_datetime', sa.DateTime(), nullable=False),
    sa.Column('sender', sa.String(), nullable=False),
    sa.Column('codepro', sa.Boolean(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('sha1_hash', sa.String(), nullable=False),
    sa.Column('unaccepted', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('traffics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('traffics')
    op.drop_table('payments')
    op.drop_table('subscriptions')
    op.drop_table('users')
    op.drop_table('subscription_types')
    # ### end Alembic commands ###
