"""edit traffics table

Revision ID: a0b8291cfdec
Revises: b7d976645b30
Create Date: 2024-03-04 22:12:12.368386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0b8291cfdec'
down_revision: Union[str, None] = 'b7d976645b30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('traffics', sa.Column('downlink', sa.BigInteger(), nullable=False))
    op.add_column('traffics', sa.Column('uplink', sa.BigInteger(), nullable=False))
    op.drop_column('traffics', 'value')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('traffics', sa.Column('value', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('traffics', 'uplink')
    op.drop_column('traffics', 'downlink')
    # ### end Alembic commands ###
