"""add redirect url

Revision ID: a16ca8a913c2
Revises: 6be815e5097c
Create Date: 2024-03-28 00:52:28.004107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a16ca8a913c2'
down_revision: Union[str, None] = '6be815e5097c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_requests', sa.Column('redirect_url', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_requests', 'redirect_url')
    # ### end Alembic commands ###
