"""payments model fix

Revision ID: b7d976645b30
Revises: 830765e30922
Create Date: 2024-03-01 00:55:58.424794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7d976645b30'
down_revision: Union[str, None] = '830765e30922'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    def upgrade() -> None:
        # ### commands auto generated by Alembic - please adjust! ###
        op.execute("ALTER TABLE payments ALTER COLUMN unaccepted TYPE BOOLEAN USING unaccepted::boolean")
        # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'unaccepted',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
