"""payments label fk payment req, payment req + tg_id 

Revision ID: d2323ba5c5cf
Revises: 2fac093ada16
Create Date: 2024-03-29 22:02:20.322172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2323ba5c5cf'
down_revision: Union[str, None] = '2fac093ada16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_requests', sa.Column('telegram_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'payments', 'payment_requests', ['label'], ['label'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_column('payment_requests', 'telegram_id')
    # ### end Alembic commands ###
