"""edit traffics system

Revision ID: d3e1fc683b9a
Revises: a0b8291cfdec
Create Date: 2024-03-05 22:10:53.569644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3e1fc683b9a'
down_revision: Union[str, None] = 'a0b8291cfdec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('periods',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('start', sa.Date(), nullable=False),
    sa.Column('stop', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('traffics', sa.Column('period_id', sa.String(), nullable=False))
    op.drop_constraint('traffics_subscription_id_fkey', 'traffics', type_='foreignkey')
    op.create_foreign_key(None, 'traffics', 'periods', ['period_id'], ['id'])
    op.drop_column('traffics', 'subscription_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('traffics', sa.Column('subscription_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'traffics', type_='foreignkey')
    op.create_foreign_key('traffics_subscription_id_fkey', 'traffics', 'subscriptions', ['subscription_id'], ['id'])
    op.drop_column('traffics', 'period_id')
    op.drop_table('periods')
    # ### end Alembic commands ###
