"""changes

Revision ID: e793aa417703
Revises: 412fe5257fac
Create Date: 2024-03-30 19:46:19.420980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e793aa417703'
down_revision: Union[str, None] = '412fe5257fac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_requests', 'sub_start')
    op.drop_column('payment_requests', 'sub_stop')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_requests', sa.Column('sub_stop', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('payment_requests', sa.Column('sub_start', sa.DATE(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
