"""changes

Revision ID: fb6af5c5491d
Revises: 9b104a6ca6b0
Create Date: 2024-03-30 00:14:09.704629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb6af5c5491d'
down_revision: Union[str, None] = '9b104a6ca6b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_requests', sa.Column('periods', sa.Integer(), nullable=False))
    op.add_column('payment_requests', sa.Column('subscription_type', sa.String(), nullable=False))
    op.create_foreign_key(None, 'payment_requests', 'subscription_types', ['subscription_type'], ['name'])
    op.drop_column('payment_requests', 'amount')
    op.drop_column('subscriptions', 'payment_label')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('payment_label', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('payment_requests', sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'payment_requests', type_='foreignkey')
    op.drop_column('payment_requests', 'subscription_type')
    op.drop_column('payment_requests', 'periods')
    # ### end Alembic commands ###
